spring:
  application:
    name: sso-uaa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
server:
  port: 8999
  context-path: /server
security:
  user:
    password: 123456