spring:
    application:
        name: CoreApplication
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
        url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
    session:
        store-type: redis    # redis 来储存session信息
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
server:
    port: 8888
    session:
      timeout: 600   # 600 秒过期，最少60秒
#debug: true

mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml

security:
  user:
    name: steve
    password: steve

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
debug: true