server:
  port: 9999
spring:
  application:
    name: steve-uaa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
debug: true
logging:
  level:
    org.springframework.security: debug
    root: debug