server:
  port: 9000
spring:
  application:
    name: steve-gateway
debug: true
logging:
  level:
    org.springframework.security: debug
    root: debug

zuul:
  sensitive-headers: "*"
  ignored-services: "*"
  routes:
    uaa:
      path: /uaa/**
      url: http://127.0.0.1:9999
    clientA:
      path: /clientA/**
      url: http://127.0.0.1:8005
    clientB:
      path: /clientB/**
      url: http://127.0.0.1:8006
