server:
  port: 8002
spring:
  application:
    name: sso-client-b
security:
  oauth2:
    client:
      client-id: ClientB
      client-secret: ClientBSecret
      access-token-uri: http://127.0.0.1:8999/server/oauth/token
      user-authorization-uri: http://127.0.0.1:8999/server/oauth/authorize
    resource:
      token-info-uri: http://127.0.0.1:8999/server/oauth/check_token # token 远程解析地址
  user:
    password: 123456

logging:
    level:
        org.springframework.security: debug
debug: true