server:
  port: 8001
spring:
  application:
    name: sso-client-a
security:
  oauth2:
    client:
      client-id: ClientA
      client-secret: ClientASecret
      access-token-uri: http://127.0.0.1:8999/server/oauth/token
      user-authorization-uri: http://127.0.0.1:8999/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8999/server/oauth/token_key   # 需要根据这个地址去获取jwt key的签名，才能解析token