spring:
    application:
        name: spring-social-base
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
        url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root

mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml

server:
    port: 1024

logging:
    level:
        org.springframework.security: DEBUG
        root: INFO

security:
    oauth2:
        client:            # 获取token的时候就需要使用到这个client-id 和 client-secret来进行Basic认证了。（fuck!!!）
            client-id: steve
            client-secret: stevesecret